.PHONY: clean All

All:
	@echo "----------Building project:[ Longest_Common_Sub_Sequence_Divide_n_Conquer - Debug ]----------"
	@cd "Longest_Common_Sub_Sequence_Divide_n_Conquer" && "$(MAKE)" -f  "Longest_Common_Sub_Sequence_Divide_n_Conquer.mk"
clean:
	@echo "----------Cleaning project:[ Longest_Common_Sub_Sequence_Divide_n_Conquer - Debug ]----------"
	@cd "Longest_Common_Sub_Sequence_Divide_n_Conquer" && "$(MAKE)" -f  "Longest_Common_Sub_Sequence_Divide_n_Conquer.mk" clean
