.PHONY: clean All

All:
	@echo "----------Building project:[ Delete_Node_without_Head_Pointer - Debug ]----------"
	@cd "Delete_Node_without_Head_Pointer" && "$(MAKE)" -f  "Delete_Node_without_Head_Pointer.mk"
clean:
	@echo "----------Cleaning project:[ Delete_Node_without_Head_Pointer - Debug ]----------"
	@cd "Delete_Node_without_Head_Pointer" && "$(MAKE)" -f  "Delete_Node_without_Head_Pointer.mk" clean
