.PHONY: clean All

All:
	@echo "----------Building project:[ First_element_occuring_k_times_in_an_array - Debug ]----------"
	@cd "First_element_occuring_k_times_in_an_array" && "$(MAKE)" -f  "First_element_occuring_k_times_in_an_array.mk"
clean:
	@echo "----------Cleaning project:[ First_element_occuring_k_times_in_an_array - Debug ]----------"
	@cd "First_element_occuring_k_times_in_an_array" && "$(MAKE)" -f  "First_element_occuring_k_times_in_an_array.mk" clean
